# Generated by Django 4.2.7 on 2023-11-05 07:25

from django.db import migrations, models
import django_choices_field.fields
import functools
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employment_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gender', models.CharField(max_length=15)),
                ('profile', models.ImageField(upload_to=functools.partial(main_app.models.make_file_path, *('image',), **{}))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField()),
                ('gender', django_choices_field.fields.TextChoicesField(choices=[('Male', 'Male'), ('Female', 'Female')], choices_enum=main_app.models.Student.TextEnum, default='Female', max_length=6)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
